server:
  port: 8080
  error:
    whitelabel:
      enabled: true

spring:
  main:
    web-application-type: REACTIVE
  threads:
    virtual:
      enabled: true

  management:
    health:
      livenessstate:
        enabled: true
      readinessstate:
        enabled: true
    endpoint:
      shutdown:
        enabled: true
      health:
        probes:
          enabled: true
        show-details: always
    info:
      build:
        enabled: true
      env:
        enabled: true
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus,loggers,beans
    prometheus:
      metrics:
        export:
          enabled: true
          descriptions: true